"""
台账管理模块领域事件
"""
from .inventory_events import (
    ApplicationCreatedEvent,
    ApplicationUpdatedEvent,
    ApplicationDeletedEvent,
    CloudResourceCreatedEvent,
    CloudResourceUpdatedEvent,
    CloudResourceDeletedEvent,
    AccountCreatedEvent,
    AccountUpdatedEvent,
    AccountDeletedEvent,
    PlanLinkedEvent,
    PlanUnlinkedEvent,
    FunctionModuleAddedEvent,
    FunctionModuleUpdatedEvent,
    FunctionModuleRemovedEvent,
    FunctionModuleCreatedEvent,
    FunctionModuleStatusChangedEvent,
    FunctionModuleDeletedEvent,
)

__all__ = [
    'ApplicationCreatedEvent',
    'ApplicationUpdatedEvent',
    'ApplicationDeletedEvent',
    'CloudResourceCreatedEvent',
    'CloudResourceUpdatedEvent',
    'CloudResourceDeletedEvent',
    'AccountCreatedEvent',
    'AccountUpdatedEvent',
    'AccountDeletedEvent',
    'PlanLinkedEvent',
    'PlanUnlinkedEvent',
    'FunctionModuleAddedEvent',
    'FunctionModuleUpdatedEvent',
    'FunctionModuleRemovedEvent',
    'FunctionModuleCreatedEvent',
    'FunctionModuleStatusChangedEvent',
    'FunctionModuleDeletedEvent',
]
